### ISSUE TITLE
How to use `disableOnDay`?

### ISSUE THREAD

**Issue by silllli** [zigomir/caly#39]
First of all: great calendar component so far! Thank you for making it.

Could you provide an example usage for the `disableOnDay` property? I would like to disable all days that are in the past, as well as some additional ones (that lie in the future).

**Comment by zigomir** [comment]
Hey, tnx :)

This example will disable all days that are past now:

```html
<script>
  const calendar = document.querySelector('caly-calendar')
  calendar.disableOnDay = (dayTimestamp) => {
    return dayTimestamp > new Date().getTime()
  }
</script>
```

**Comment by silllli** [comment]
Ah now I get it, it needs to be a function. Thank you!
